### ISSUE TITLE
Feature Request: Add Unicode support

### ISSUE THREAD

**Issue by hdmariner** [tdobrovolskij/sanguinews#30]
Currently I am getting a deadlock error while trying to upload file that is written in Asian characters.  I am using a low end system but think the error is due to unicode not being supported since the program works with files that have Western charset names.

**Comment by tdobrovolskij** [comment]
According to official standards, usenet is ASCII only. The providers I have tested sanguinews with do not allow unicode names. What's the name of the provider you are using? Do they allow normally to upload files with Asian characters? Have you tested it with other binary uploaders?

**Comment by hdmariner** [comment]
Sorry, my bad.  You can close this.
